### ISSUE TITLE
not connecting to the host

### ISSUE THREAD

**Issue by abdesstis** [Dolphin-Bunny/Impostor-Replit-Tutorial#1]
its not connecting to the ip adress and i beileve i done evrything right

**Comment by Dolphin-Bunny** [comment]
@abdesstis
Sorry I didn't see this sooner,

I'm assuming you followed the instructions on the Imposter repository?
Are there any errors in the console? 

Also, I saw on your fork you renamed the `.sh` files to `.py`. Since they are written not written in python, running them as python scripts will not work

I don't have any idea if this will work, but you could try changing the values of `PublicPort` and `ListenPort` to `8080` in `config.json`, and then try connecting to port `8080` of your repl instead of `22023`

Also, this repository will use the in-development branch of Imposter, which could have more bugs. As far as I can tell, currently the only advantage the development branch has over the release branch is plugin support (super excited to try it out). If you don't care about plugins, you can use [these instructions](https://github.com/Dolphin-Bunny/imposter-replit-basic)

Apologies for the inconvenience

**Comment by abdesstis** [comment]
i folowed all the instructions and its running fine but when i try to connect to the repl domain it says You disconnected from the server retiable packet 1  and i also renamed it to .py bcause it doasnt let me git clone it when i cloned it i change it back tp .sh

**Comment by abdesstis** [comment]
and also i tryed to connect to connect to impostor-real.dolphinbunny.repl.co and still giving me the same problem

**Comment by Dolphin-Bunny** [comment]
ok
when you say you tried to connect to the repl domain, did you try to connect to the replname.yourusername.repl.co one, or did you connect to the ip address?

also, whether or not you want plugins, you could try the other instructions (https://github.com/Dolphin-Bunny/imposter-replit-basic), just to see if its something with repl.it or my directions.

Again, sorry for any inconvenience

(I agree, heroku is a nightmare to set up)

*edit:* I am getting a similar message
*edit 2:* I am still getting the message when running it on a vm on my computer

**Comment by abdesstis** [comment]
Yes i connected to the repl domain and the public ip by using the command curl ipecho.net/plain and still didnt work i also tryed heroku and it didnt even deploy from github.Its working but i cant connect to it

**Comment by Dolphin-Bunny** [comment]
I'm very sorry it isn't working, I'll let you know if I get it to work

Idk if it's something with the server, VMs in general, or something else

Again, sorry about that

Cheers

**Comment by abdesstis** [comment]
add me as a discord friend on discord: Abdesstis#4444

**Comment by abdesstis** [comment]
please add my discord i want tell you aboutb something

**Comment by Dolphin-Bunny** [comment]
Ok, I sent a request (from Dolphin)

Sorry I didn't see this sooner, I don't check Github that often when I'm not working on a new project
